version: '3.6'
services:
  kafka-tools:
    networks:
      - localnet
    build:
      context: ./kafka-tools
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - ./data:/root/data
networks:
  localnet:
    attachable: true
